# MOUSEKEY_ENABLE = no
# MIDI_ENABLE = no
# AUDIO_ENABLE = no
UNICODE_ENABLE = no
# BLUETOOTH_ENABLE = no
TAP_DANCE_ENABLE = yes
CONSOLE_ENABLE = no


# BACKLIGHT_ENABLE = no
# BACKLIGHT_CUSTOM_DRIVER = no

# RGBLIGHT_ENABLE = no
# RGBLIGHT_CUSTOM_DRIVER = no

# SLEEP_LED_ENABLE = no

MOUSEKEY_ENABLE = yes
LINK_TIME_OPTIMIZATION_ENABLE = yes
EXTRAFLAGS += -flto
